version: '3'
services:
  nginx:
    container_name: cv-site-nginx
    image: nginx:1.15-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./cv:/var/www/palchukdenis.com
      - ./letsencrypt/certbot/conf:/etc/letsencrypt
      - ./letsencrypt/certbot/www:/var/www/certbot
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
  certbot:
    container_name: certbot-container
    image: certbot/certbot
    volumes:
      - ./letsencrypt/certbot/conf:/etc/letsencrypt
      - ./letsencrypt/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
