- name: Upload image to server
  hosts: app
  tasks:
    - name: Install git and pip3
      apt:
        name: 
          - git
          - python3-pip

    - name: Install docker module to python
      pip:
        name:
        - docker
        - docker-compose
        - requests>=2.20.1

    - name: Remove prev version of application
      file:
        path: ~/cv-site
        state: absent

    - name: clone repo from git
      git:
        repo: 'https://github.com/DenisPalchuk/cv-site.git'
        dest: ~/cv-site
        force: yes

    - name: Stop old nginx and let's encrypt container
      docker_compose:
        project_src: ~/cv-site
        state: absent
        stopped: yes

    # Docker-compose module doesn't support adhoc running so it's just a workaround
    - name: Creating dummy certificate for palchukdenis.com
      shell:
        cmd: docker-compose run --rm --entrypoint "\
          openssl req -x509 -nodes -newkey rsa:1024 -days 1\
          -keyout '/etc/letsencrypt/live/palchukdenis.com/privkey.pem' \
          -out '/etc/letsencrypt/live/palchukdenis.com/fullchain.pem' \
          -subj '/CN=localhost'" certbot
        chdir: ~/cv-site

    - name: Starting nginx
      docker_compose:
        services:
          - nginx
        project_src: ~/cv-site
        recreate: always


