- name: Upload image to server
  hosts: app
  tasks:
    - name: Install git and pip3
      apt:
        name: git python3-pip

    - name: Install docker module to python
      pip:
        name:
        - docker
        - docker-compose
        - requests>=2.20.1

    - name: clone repo from git
      git:
        repo: 'https://github.com/DenisPalchuk/cv-site.git'
        dest: ~/
      
    
    - name: Run App container
      docker-_compose:
        project_src: ~/cv-site
