name: Publish Docker image

on: [push]

jobs:

  deploy:

    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v1
        
        - name: Add private key to ssh-agent
          run: |
            touch ./key.pem
            echo "${{ secrets.SSH_PRIVATE_KEY }}" >> ./key.pem
            chmod 700 ./key.pem 
        
        - name: Setting up services by docker-compose 
          uses: saubermacherag/ansible-playbook-docker-action@v1.2
          with:
            playbookName: '.ansible/upload-to-server.yml'
            inventoryFile: '.ansible/production/inventory.yml'
            keyFile: './key.pem'
            extraVars: "-e docker_username=${{ secrets.DOCKER_USERNAME }} -e docker_password=${{ secrets.DOCKER_PASSWORD }}" 
